### ISSUE TITLE
timeshiftBufferDepth is optional when MPD@type is static

### ISSUE THREAD

**Issue by tlohmar** [Dash-Industry-Forum/Conformance-Software#166]
The MPD conformance check does not allow TSB, when MPD@type is static.

According to DASH:2016, the presence of the TSB is optional. There is no restriction on the presence for static MPDs.

**Comment by waqarz** [comment]
Can you please post the MPD or URL? This error should only be there if there is DASH-IF profile identifier, as DASH-IF does not allow TSB for static MPD

**Comment by waqarz** [comment]
Discussed here: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/120

**Comment by AdithyanIlangovan** [comment]
@tlohmar 
Thanks for reporting the issue.

Earlier, the bug was that irrespective of the profile, the conformance software checks for:
`timeShiftBufferDepth should not be present when type == static`

This issue is fixed now in #171.
Now, this check is performed only if the DASH-IF IOP profile is specified in the .mpd.

The code has been updated. 
It might take a while before the changes are reflected in the server.
I would request to check your .mpd again.
If errors persist, please report.
