### ISSUE TITLE
Breaks down for HDR vectors

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#182]
- Strange broken URL list.
- Still problem of reporting "segment timeline".
- Binary crashes on most reps.

**Comment by waqarz** [comment]
http://dash.akamaized.net/dash264/TestCasesHDR/3a/1/MultiRate.mpd
http://dash.akamaized.net/dash264/TestCasesHDR/3b/1/MultiRate.mpd

**Comment by joywelt** [comment]
Fixed the binary crash and "segment timeline". Investigated into the broken URL issue. 

- The problem in the first test vector is gone.
- For the second test vector it still have this problem, because there is no "baseURL" element, and it's using "initialization" element to find the segment URLs, which is not supported yet by the conformance software. We could add this function if required.
