### ISSUE TITLE
Outdated MIMEType error

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#200]
location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][3]">
DASH-IF IOP (v3.3) Section 3.2.13: For Adaptation Sets the mimeType shall be one of the four following type: "video/mp4", "audio/mp4", or "application/mp4"

Also this is being thrown for non-DASH-IF content;

This check is not there anymore in IOP guidelines; there is also new added MIME Types on VTT

**Comment by waqarz** [comment]
We should review the IOP v3.3/4.0 and gather all the mime types there could be and throw this error appropriately

**Comment by AdithyanIlangovan** [comment]
Okay. 
So, since this check is not present anymore in IOP 4.0, I will remove the conformance check that corresponds to : 

> DASH-IF IOP (v3.3) Section 3.2.13: For Adaptation Sets the mimeType shall be one of the four following type: "video/mp4", "audio/mp4", or "application/mp4"

I searched the IOP 4.0 for shall conditions related to mimeType. I found only two 

1. "Representations with @mimeType attribute application/xml+ttml shall not be ignored."
2. One specific condition when two adaptations sets in one MPD are period-continous. In such a case, the conditions, is "@mimeType attribute for the Representation in the next Period shall be the same as one of the first Period."

**Comment by waqarz** [comment]
I would suggest to have a rule as follows:

- If DASH-IF profile identifier is present, compare MIME type to the list of all possible MIME types (found anywhere in the IOP in addition to "video/mp4", "audio/mp4",  "application/mp4"). If MIME type is not matched, we should raise an error of an unexpected MIME type in DASH-IF conforming MPD.

**Comment by AdithyanIlangovan** [comment]
Will go ahead and implement this rule.

**Comment by AdithyanIlangovan** [comment]
Final clarification. 
Although, the DASH-IF IOP does not explicitly state any shall condition for the "type" of mimeType, 
I will implement the following condition for DASH-IF profile identifiers in the conformance tool.

> For Adaptation Sets the mimeType shall be one of the five following type: "video/mp4", "audio/mp4", "application/mp4", "application/ttml+xml" or "text/vtt"

**Comment by AdithyanIlangovan** [comment]
Solved in #201.
Closing now, and if issues exist please reopen.
