### ISSUE TITLE
Conformance tool failing asserts for static MPD like it's a dynamic one

### ISSUE THREAD

**Issue by UnitasBrooks** [Dash-Industry-Forum/Conformance-Software#53]
I have a static MPD the dash tool treats it like a dynamic one and gives the following output:
     [java]
     [java] Start XLink resolving
     [java] =====================
     [java]
     [java] XLink resolving successful
     [java]
     [java]
     [java]
     [java] Start MPD validation
     [java] ====================
     [java]
     [java] MPD validation successful - DASH is valid!
     [java]
     [java]
     [java]
     [java] Start Schematron validation
     [java] ===========================
     [java]
     [java] <svrl:failed-assert test="if (@type = 'dynamic' and not(@publishTime)) then false() else true()"
     [java]                        location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
     [java]       <svrl:text>If MPD is of type "dynamic" publishTime shall be defined.</svrl:text>
     [java]    </svrl:failed-assert>
     [java] <svrl:failed-assert test="if (@type='dynamic' and not(@id)) then false() else true()"
     [java]                        location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
     [java]       <svrl:text>If the MPD type is dynamic, the id shall be present </svrl:text>
     [java]    </svrl:failed-assert>
     [java] Schematron validation not successful - DASH is not valid!
     [java]
     [java]

MPD: https://gist.github.com/UnitasBrooks/7599ea8a5651bf87aa28

**Comment by waqarz** [comment]
I have published the MPD here: https://e6d9d3cb65a3908ad212b00f146b1f15ab70ceef-www.googledrive.com/host/0B4L8oPUb48JTcGhObzNFRXpvVUU and when I run conformance, it reports it is conforming: (obviously representations would be broken since I dont have media data)
![image](https://cloud.githubusercontent.com/assets/3089913/6914721/afaf7cec-d78d-11e4-81ba-5cb905cf7217.png)

Please try again. Though a lot of extra spaces in the attribute xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/ PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" in the MPD are strange and my cause problems.

**Comment by waqarz** [comment]
I am closing this, please reopen if you still have an issue.
